# fly.toml app configuration file generated for movies-api-movieflix on 2024-04-08T14:56:54-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'movies-api-movieflix'
primary_region = 'qro'

[experimental]
  auto_rollback = true

[build]
  image = 'd4nilo/movies-api'

[env]
  MOVIES_SERVICE_PORT = "${MOVIES_SERVICE_PORT}"
  PORT = "${APP_PORT}"
  NODE_ENV = "production"
  MONGO_URI = "${MONGO_URI}"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 3000

[[services.ports]]
    port = 80
    handlers = ['http']

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
